CREATE USER bxcode;
CREATE DATABASE bxcode_db;
GRANT ALL PRIVILEGES ON DATABASE bxcode_db to bxcode;

DROP TABLE IF EXISTS public.TBL_DEMO;
CREATE TABLE IF NOT EXISTS public.TBL_PERSON
(
    PE_ID NUMERIC(38, 0) NOT NULL,
    CONSTRAINT TBL_PERSON_PK PRIMARY KEY (PE_ID)
);

INSERT INTO public.TBL_PERSON(PE_ID)
VALUES (1),
       (2),
       (3),
       (4),
       (5);