version: '3.9'
services:
  postgres:
    build:
      context: images
      target: ${POSTGRES_TARGET}
      dockerfile: ${POSTGRES_FILE}
    image: ${POSTGRES_IMAGE}
    container_name: bxcode-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./scripts/ep-cinfe-statistic-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cinfe
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: bxcode-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_ADDR: postgres
      DB_PORT: ${POSTGRES_PORT}
      DB_SCHEMA: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - start-dev
    networks:
      - cinfe

networks:
  cinfe:
    driver: bridge