version: '3.9'
services:
  jenkins:
    build:
      context: images
      target: dev
      dockerfile: jenkins.dockerfile
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/jenkins:/var/jenkins_home
    networks:
      - cinfe

  postgres:
    build:
      context: images
      target: dev
      dockerfile: postgres.dockerfile
    container_name: bxcode-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./scripts/ep-cinfe-statistic-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cinfe

  sonarqube:
    build:
      context: images
      target: dev
      dockerfile: sonar.dockerfile
    container_name: bxcode-sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/postgres
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    restart: always
    depends_on:
      - postgres
    networks:
      - cinfe




  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: bxcode-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_ADDR: postgres
      DB_PORT: ${POSTGRES_PORT}
      DB_SCHEMA: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - start-dev
    networks:
      - cinfe

networks:
  cinfe:
    driver: bridge