DROP TABLE IF EXISTS public.EP_PROFILE_OPTION_MODULE;
DROP TABLE IF EXISTS public.EP_MODULE;
DROP TABLE IF EXISTS public.EP_USER;
DROP TABLE IF EXISTS public.EP_PROFILE;
DROP TABLE IF EXISTS public.EP_PERSON;
DROP TABLE IF EXISTS public.EP_MODULE_STATUS;
DROP TABLE IF EXISTS public.EP_PROFILE_STATUS;
DROP TABLE IF EXISTS public.EP_USER_STATUS;
DROP TABLE IF EXISTS public.EP_UNIT;
DROP TABLE IF EXISTS public.EP_BRIGADE;
DROP TABLE IF EXISTS public.EP_DIVISION;
DROP TABLE IF EXISTS public.EP_DIVISION_STATUS;

DROP SEQUENCE IF EXISTS EP_MODULE_STATUS_SEQ;
DROP SEQUENCE IF EXISTS EP_MODULE_SEQ;
DROP SEQUENCE IF EXISTS EP_PERSON_SEQ;
DROP SEQUENCE IF EXISTS EP_USER_STATUS_SEQ;
DROP SEQUENCE IF EXISTS EP_PROFILE_STATUS_SEQ;
DROP SEQUENCE IF EXISTS EP_PROFILE_SEQ;
DROP SEQUENCE IF EXISTS EP_USER_SEQ;
DROP SEQUENCE IF EXISTS EP_PROFILE_OPTION_MODULE_SEQ;
DROP SEQUENCE IF EXISTS EP_UNIT_SEQ;
DROP SEQUENCE IF EXISTS EP_BRIGADE_SEQ;
DROP SEQUENCE IF EXISTS EP_DIVISION_SEQ;
DROP SEQUENCE IF EXISTS EP_DIVISION_STATUS_SEQ;

CREATE TABLE IF NOT EXISTS public.EP_MODULE_STATUS
(
    MS_ID          NUMERIC(38, 0) NOT NULL,
    MS_UUID        VARCHAR(36)    NOT NULL,
    MS_CODE        VARCHAR(30)    NOT NULL,
    MS_NAME        VARCHAR(50)    NOT NULL,
    MS_DESCRIPTION VARCHAR(100),
    CONSTRAINT EP_MODULE_STATUS_PK PRIMARY KEY (MS_ID),
    CONSTRAINT EP_MODULE_STATUS_UN1 UNIQUE (MS_UUID),
    CONSTRAINT EP_MODULE_STATUS_UN2 UNIQUE (MS_CODE),
    CONSTRAINT EP_MODULE_STATUS_UN3 UNIQUE (MS_NAME)
);

CREATE TABLE IF NOT EXISTS public.EP_MODULE
(
    MO_ID            NUMERIC(38, 0)       NOT NULL,
    MO_UUID          VARCHAR(36)          NOT NULL,
    MO_MODULE_STATUS NUMERIC(38, 0)       NOT NULL,
    MO_NAME          VARCHAR(50)          NOT NULL,
    MO_IS_COMPONENT  NUMERIC(1) DEFAULT 0 NOT NULL,
    MO_IS_MENU       NUMERIC(1) DEFAULT 0 NOT NULL,
    MO_ICON          VARCHAR(50),
    MO_PATH          VARCHAR(50),
    MO_ORDER         NUMERIC(1)           NOT NULL,
    MO_GROUP         NUMERIC(1)           NOT NULL,
    MO_CREATE_DATE   TIMESTAMP(6)         NOT NULL,
    MO_UPDATE_DATE   TIMESTAMP(6),
    CONSTRAINT EP_MODULE_PK PRIMARY KEY (MO_ID),
    CONSTRAINT EP_MODULE_UN1 UNIQUE (MO_UUID),
    CONSTRAINT EP_MODULE_UN2 UNIQUE (MO_NAME),
    CONSTRAINT EP_MODULE_FK FOREIGN KEY (MO_MODULE_STATUS) REFERENCES EP_MODULE_STATUS (MS_ID)
);

CREATE TABLE IF NOT EXISTS public.EP_PERSON
(
    PE_ID       NUMERIC(38, 0) NOT NULL,
    PE_UUID     VARCHAR(36)    NOT NULL,
    PE_NAME     VARCHAR(50)    NOT NULL,
    PE_LASTNAME VARCHAR(50)    NOT NULL,
    PE_DOB      TIMESTAMP(6)   NOT NULL,
    CONSTRAINT EP_PERSON_PK PRIMARY KEY (PE_ID),
    CONSTRAINT EP_PERSON_UN1 UNIQUE (PE_UUID)
);

CREATE TABLE IF NOT EXISTS public.EP_USER_STATUS
(
    US_ID          NUMERIC(38, 0) NOT NULL,
    US_UUID        VARCHAR(36)    NOT NULL,
    US_CODE        VARCHAR(30)    NOT NULL,
    US_NAME        VARCHAR(50)    NOT NULL,
    US_DESCRIPTION VARCHAR(100),
    CONSTRAINT EP_USER_STATUS_PK PRIMARY KEY (US_ID),
    CONSTRAINT EP_USER_STATUS_UN1 UNIQUE (US_UUID),
    CONSTRAINT EP_USER_STATUS_UN2 UNIQUE (US_CODE),
    CONSTRAINT EP_USER_STATUS_UN3 UNIQUE (US_NAME)
);

CREATE TABLE IF NOT EXISTS public.EP_PROFILE_STATUS
(
    PS_ID          NUMERIC(38, 0) NOT NULL,
    PS_UUID        VARCHAR(36)    NOT NULL,
    PS_CODE        VARCHAR(30)    NOT NULL,
    PS_NAME        VARCHAR(50)    NOT NULL,
    PS_DESCRIPTION VARCHAR(100),
    CONSTRAINT EP_PROFILE_STATUS_PK PRIMARY KEY (PS_ID),
    CONSTRAINT EP_PROFILE_STATUS_UN1 UNIQUE (PS_UUID),
    CONSTRAINT EP_PROFILE_STATUS_UN2 UNIQUE (PS_CODE),
    CONSTRAINT EP_PROFILE_STATUS_UN3 UNIQUE (PS_NAME)
);

CREATE TABLE IF NOT EXISTS public.EP_PROFILE
(
    PR_ID          NUMERIC(38, 0) NOT NULL,
    PR_UUID        VARCHAR(36)    NOT NULL,
    PR_ROLE_STATUS NUMERIC(38, 0) NOT NULL,
    PR_NAME        VARCHAR(50)    NOT NULL,
    CONSTRAINT EP_PROFILE_PK PRIMARY KEY (PR_ID),
    CONSTRAINT EP_PROFILE_UN1 UNIQUE (PR_UUID),
    CONSTRAINT EP_PROFILE_FK1 FOREIGN KEY (PR_ROLE_STATUS) REFERENCES EP_PROFILE_STATUS (PS_ID)
);

CREATE TABLE IF NOT EXISTS public.EP_USER
(
    US_ID          NUMERIC(38, 0) NOT NULL,
    US_UUID        VARCHAR(36)    NOT NULL,
    US_PERSON_ID   NUMERIC(38, 0) NOT NULL,
    US_PROFILE_ID  NUMERIC(38, 0) NOT NULL,
    US_USER_STATUS NUMERIC(38, 0) NOT NULL,
    US_USERNAME    VARCHAR(50)    NOT NULL,
    US_PASSWORD    VARCHAR(50)    NOT NULL,
    US_CREATE_DATE TIMESTAMP(6)   NOT NULL,
    US_UPDATE_DATE TIMESTAMP(6),
    CONSTRAINT EP_USER_PK PRIMARY KEY (US_ID),
    CONSTRAINT EP_USER_UN1 UNIQUE (US_UUID),
    CONSTRAINT EP_USER_FK1 FOREIGN KEY (US_PERSON_ID) REFERENCES EP_PERSON (PE_ID),
    CONSTRAINT EP_USER_FK2 FOREIGN KEY (US_PROFILE_ID) REFERENCES EP_PROFILE (PR_ID),
    CONSTRAINT EP_USER_FK3 FOREIGN KEY (US_USER_STATUS) REFERENCES EP_USER_STATUS (US_ID)
);

CREATE TABLE IF NOT EXISTS public.EP_PROFILE_OPTION_MODULE
(
    POS_ID          NUMERIC(38, 0) NOT NULL,
    POS_UUID        VARCHAR(36)    NOT NULL,
    POS_MODULE_ID   NUMERIC(38, 0) NOT NULL,
    POS_PROFILE_ID  NUMERIC(38, 0) NOT NULL,
    POS_PRIVILEGES  VARCHAR(50)    NOT NULL,
    POS_CREATE_DATE TIMESTAMP(6)   NOT NULL,
    POS_UPDATE_DATE TIMESTAMP(6),
    CONSTRAINT EP_PROFILE_OPTION_MODULE_PK PRIMARY KEY (POS_ID),
    CONSTRAINT EP_PROFILE_OPTION_MODULE_UN1 UNIQUE (POS_UUID),
    CONSTRAINT EP_PROFILE_OPTION_MODULE_FK1 FOREIGN KEY (POS_MODULE_ID) REFERENCES EP_MODULE (MO_ID),
    CONSTRAINT EP_PROFILE_OPTION_MODULE_FK2 FOREIGN KEY (POS_PROFILE_ID) REFERENCES EP_PROFILE (PR_ID)
);


CREATE TABLE public.EP_DIVISION_STATUS
(
    DS_ID          NUMERIC(38, 0) NOT NULL,
    DS_UUID        VARCHAR(36)    NOT NULL,
    DS_CODE        VARCHAR(11)     NOT NULL,
    DS_NAME        VARCHAR(11)     NOT NULL,
    DS_DESCRIPTION VARCHAR(20),
    CONSTRAINT EP_DIVISION_STATUS_PK PRIMARY KEY (DS_ID),
    CONSTRAINT EP_DIVISION_STATUS_UN1 UNIQUE (DS_UUID),
    CONSTRAINT EP_DIVISION_STATUS_UN2 UNIQUE (DS_CODE),
    CONSTRAINT EP_DIVISION_STATUS_UN3 UNIQUE (DS_NAME)
);

CREATE TABLE public.EP_DIVISION
(
    DI_ID           NUMERIC(38, 0) NOT NULL,
    DI_UUID         VARCHAR(36)    NOT NULL,
    DI_STATUS       NUMERIC(38, 0) NOT NULL,
    DI_CODE         VARCHAR(2)     NOT NULL,
    DI_NAME         VARCHAR(60)    NOT NULL,
    DI_DESCRIPTION  VARCHAR(120),
    DI_CREATED_DATE TIMESTAMP(6)   NOT NULL,
    DI_UPDATED_DATE TIMESTAMP(6),
    CONSTRAINT EP_DIVISION_PK PRIMARY KEY (DI_ID),
    CONSTRAINT EP_DIVISION_UN1 UNIQUE (DI_UUID),
    CONSTRAINT EP_DIVISION_UN2 UNIQUE (DI_CODE),
    CONSTRAINT EP_DIVISION_UN3 UNIQUE (DI_NAME),
    CONSTRAINT EP_DIVISION_FK FOREIGN KEY (DI_STATUS) REFERENCES EP_DIVISION_STATUS (DS_ID)
);
CREATE TABLE public.EP_BRIGADE
(
    BR_ID           NUMERIC(38, 0) NOT NULL,
    BR_UUID         VARCHAR(36)    NOT NULL,
    BR_DIVISION_ID  NUMERIC(38, 0) NOT NULL,
    BR_CODE         VARCHAR(4)     NOT NULL,
    BR_NAME         VARCHAR(60)    NOT NULL,
    BR_DESCRIPTION  VARCHAR(120),
    BR_CREATED_DATE TIMESTAMP(6)   NOT NULL,
    BR_UPDATED_DATE TIMESTAMP(6),
    CONSTRAINT EP_BRIGADE_PK PRIMARY KEY (BR_ID),
    CONSTRAINT EP_BRIGADE_UN1 UNIQUE (BR_UUID),
    CONSTRAINT EP_BRIGADE_UN2 UNIQUE (BR_CODE),
    CONSTRAINT EP_BRIGADE_UN3 UNIQUE (BR_NAME),
    CONSTRAINT EP_BRIGADE_FK1 FOREIGN KEY (BR_DIVISION_ID) REFERENCES EP_DIVISION (DI_ID)
);
CREATE TABLE public.EP_UNIT
(
    UN_ID             NUMERIC(38, 0) NOT NULL,
    UN_UUID           VARCHAR(36)    NOT NULL,
    UN_BRIGADE_STATUS NUMERIC(38, 0) NOT NULL,
    UN_CODE           VARCHAR(6)     NOT NULL,
    UN_NAME           VARCHAR(60)    NOT NULL,
    UN_DESCRIPTION    VARCHAR(120),
    UN_CREATED_DATE   TIMESTAMP(6)   NOT NULL,
    UN_UPDATED_DATE   TIMESTAMP(6),
    CONSTRAINT EP_UNIT_PK PRIMARY KEY (UN_ID),
    CONSTRAINT EP_UNIT_UN1 UNIQUE (UN_UUID),
    CONSTRAINT EP_UNIT_UN2 UNIQUE (UN_CODE),
    CONSTRAINT EP_UNIT_UN3 UNIQUE (UN_NAME),
    CONSTRAINT EP_UNIT_FK FOREIGN KEY (UN_BRIGADE_STATUS) REFERENCES EP_BRIGADE (BR_ID)
);
-- CREATE SEQUENCE FOR TABLES
CREATE SEQUENCE IF NOT EXISTS public.EP_MODULE_STATUS_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;
CREATE SEQUENCE IF NOT EXISTS public.EP_MODULE_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;
CREATE SEQUENCE IF NOT EXISTS public.EP_PERSON_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;
CREATE SEQUENCE IF NOT EXISTS public.EP_USER_STATUS_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;
CREATE SEQUENCE IF NOT EXISTS public.EP_PROFILE_STATUS_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;
CREATE SEQUENCE IF NOT EXISTS public.EP_PROFILE_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;
CREATE SEQUENCE IF NOT EXISTS public.EP_USER_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;
CREATE SEQUENCE IF NOT EXISTS public.EP_PROFILE_OPTION_MODULE_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;
CREATE SEQUENCE IF NOT EXISTS public.EP_DIVISION_STATUS_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;

CREATE SEQUENCE IF NOT EXISTS public.EP_DIVISION_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;

CREATE SEQUENCE IF NOT EXISTS public.EP_BRIGADE_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;

CREATE SEQUENCE IF NOT EXISTS public.EP_UNIT_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999999999999
    START 1;

--FILL DATA IN TABLE EP_USER_STATUS
INSERT INTO EP_USER_STATUS(US_ID, US_UUID, US_CODE, US_NAME, US_DESCRIPTION)
VALUES (nextval('EP_USER_STATUS_SEQ'), gen_random_uuid(), 'USER_ACTIVE', 'USER ACTIVE', 'USER ACTIVE'),
       (nextval('EP_USER_STATUS_SEQ'), gen_random_uuid(), 'USER_INACTIVE', 'USER INACTIVE', 'USER INACTIVE');

SELECT *
FROM EP_USER_STATUS;

--FILL DATA IN TABLE EP_PROFILE_STATUS
INSERT INTO EP_PROFILE_STATUS(PS_ID, PS_UUID, PS_CODE, PS_NAME, PS_DESCRIPTION)
VALUES (nextval('EP_PROFILE_STATUS_SEQ'), gen_random_uuid(), 'PROFILE_ACTIVE', 'PROFILE ACTIVE', 'PROFILE ACTIVE'),
       (nextval('EP_PROFILE_STATUS_SEQ'), gen_random_uuid(), 'PROFILE_INACTIVE', 'PROFILE INACTIVE',
        'PROFILE INACTIVE');

SELECT *
FROM EP_PROFILE_STATUS;

--FILL DATA IN TABLE EP_MODULE_STATUS
INSERT INTO EP_MODULE_STATUS(MS_ID, MS_UUID, MS_CODE, MS_NAME, MS_DESCRIPTION)
VALUES (nextval('EP_MODULE_STATUS_SEQ'), gen_random_uuid(), 'MODULE_ACTIVE', 'MODULE ACTIVE', 'MODULE ACTIVE'),
       (nextval('EP_MODULE_STATUS_SEQ'), gen_random_uuid(), 'MODULE_INACTIVE', 'MODULE INACTIVE',
        'MODULE INACTIVE');

SELECT *
FROM EP_MODULE_STATUS;

--FILL DATA IN TABLE EP_PERSON
INSERT INTO EP_PERSON(PE_ID, PE_UUID, PE_NAME, PE_LASTNAME, PE_DOB)
VALUES (nextval('EP_PERSON_SEQ'), gen_random_uuid(), 'CHRISTIAN DAVID', 'BACILIO DE LA CRUZ', '1988-01-19 00:00:00'),
       (nextval('EP_PERSON_SEQ'), gen_random_uuid(), 'FAUSTINA MERCEDES', 'DEL ROSARIO SOBRINO', '1997-09-09 00:00:00');

SELECT *
FROM EP_PERSON;

--FILL DATA IN TABLE EP_PROFILE
INSERT INTO EP_PROFILE(PR_ID, PR_UUID, PR_ROLE_STATUS, PR_NAME)
VALUES (nextval('EP_PROFILE_SEQ'), gen_random_uuid(), 1, 'SUPER'),
       (nextval('EP_PROFILE_SEQ'), gen_random_uuid(), 1, 'ADMINISTRADOR');

SELECT *
FROM EP_PROFILE;

--FILL DATA IN TABLE EP_USER
INSERT INTO EP_USER(US_ID, US_UUID, US_PERSON_ID, US_PROFILE_ID, US_USER_STATUS, US_USERNAME, US_PASSWORD,
                    US_CREATE_DATE, US_UPDATE_DATE)
VALUES (nextval('EP_USER_SEQ'), gen_random_uuid(), 1, 1, 1, 'CBACILIOD', '123', current_timestamp, null),
       (nextval('EP_USER_SEQ'), gen_random_uuid(), 2, 2, 1, 'FDELROSARIOS', '123', current_timestamp, null);

SELECT *
FROM EP_USER;

--FILL DATA IN TABLE EP_MODULE
INSERT INTO EP_MODULE(MO_ID, MO_UUID, MO_MODULE_STATUS, MO_NAME, MO_IS_COMPONENT, MO_IS_MENU, MO_ICON, MO_PATH,
                      MO_ORDER, MO_GROUP, MO_CREATE_DATE, MO_UPDATE_DATE)
VALUES (nextval('EP_MODULE_SEQ'), gen_random_uuid(), 1, 'SEGURIDAD', 1, 1, 'icon-1', 'path-1', 1, 1, current_timestamp,
        null),
       (nextval('EP_MODULE_SEQ'), gen_random_uuid(), 1, 'DASHBOARD', 1, 1, 'icon-1', 'path-1', 1, 1, current_timestamp,
        null),
       (nextval('EP_MODULE_SEQ'), gen_random_uuid(), 1, 'REPORTES', 1, 1, 'icon-1', 'path-1', 1, 1, current_timestamp,
        null);

SELECT *
FROM EP_MODULE;

--FILL DATA IN TABLE EP_PROFILE_OPTION_MODULE
INSERT INTO EP_PROFILE_OPTION_MODULE(POS_ID, POS_UUID, POS_MODULE_ID, POS_PROFILE_ID, POS_PRIVILEGES, POS_CREATE_DATE,
                                     POS_UPDATE_DATE)
VALUES (nextval('EP_PROFILE_OPTION_MODULE_SEQ'), gen_random_uuid(), 1, 1, 'true,true,true,true,true,true,true,true',
        current_timestamp, null),
       (nextval('EP_PROFILE_OPTION_MODULE_SEQ'), gen_random_uuid(), 1, 1, 'true,true,true,true,true,true,true,true',
        current_timestamp, null),
       (nextval('EP_PROFILE_OPTION_MODULE_SEQ'), gen_random_uuid(), 1, 1, 'true,true,true,true,true,true,true,true',
        current_timestamp, null);

SELECT *
FROM EP_PROFILE_OPTION_MODULE;


INSERT INTO EP_DIVISION_STATUS(DS_ID, DS_UUID, DS_CODE, DS_NAME, DS_DESCRIPTION)
VALUES (nextval('EP_DIVISION_STATUS_SEQ'), gen_random_uuid(), 'ACTIVATED', 'ACTIVATED', 'DIVISION ACTIVATED'),
       (nextval('EP_DIVISION_STATUS_SEQ'), gen_random_uuid(), 'INACTIVATED', 'INACTIVATED', 'DIVISION INACTIVATED');

SELECT * FROM EP_DIVISION_STATUS WHERE DS_ID = 1;
