DROP TABLE IF EXISTS public.EP_MODULE_STATUS;
CREATE TABLE IF NOT EXISTS public.EP_MODULE_STATUS
(
    MS_ID          NUMERIC(38, 0) NOT NULL,
    MS_UUID        VARCHAR(36)    NOT NULL,
    MS_CODE        VARCHAR(30)    NOT NULL,
    MS_NAME        VARCHAR(50)    NOT NULL,
    MS_DESCRIPTION VARCHAR(100),
    CONSTRAINT EP_MODULE_STATUS_PK PRIMARY KEY (MS_ID),
    CONSTRAINT EP_MODULE_STATUS_UN1 UNIQUE (MS_UUID),
    CONSTRAINT EP_MODULE_STATUS_UN2 UNIQUE (MS_CODE),
    CONSTRAINT EP_MODULE_STATUS_UN3 UNIQUE (MS_NAME)
);

DROP TABLE IF EXISTS public.EP_MODULE;
CREATE TABLE IF NOT EXISTS public.EP_MODULE
(
    MO_ID            NUMERIC(38, 0) NOT NULL,
    MO_UUID          VARCHAR(36)    NOT NULL,
    MO_MODULE_STATUS NUMERIC(38, 0) NOT NULL,
    MO_NAME          VARCHAR(50)    NOT NULL,
    MO_CREATE_DATE   TIMESTAMP(6)   NOT NULL,
    MO_UPDATE_DATE   TIMESTAMP(6),
    CONSTRAINT EP_MODULE_PK PRIMARY KEY (MO_ID),
    CONSTRAINT EP_MODULE_UN1 UNIQUE (MO_UUID),
    CONSTRAINT EP_MODULE_UN2 UNIQUE (MO_NAME),
    CONSTRAINT EP_MODULE_FK FOREIGN KEY (MO_MODULE_STATUS) REFERENCES EP_MODULE_STATUS (MS_ID)
);



DROP TABLE IF EXISTS public.EP_PERSON;
CREATE TABLE IF NOT EXISTS public.EP_PERSON
(
    PE_ID       NUMERIC(38, 0) NOT NULL,
    PE_NAME     VARCHAR(50)    NOT NULL,
    PE_LASTNAME VARCHAR(50)    NOT NULL,
    PE_DOB      TIMESTAMP(6)   NOT NULL,
    CONSTRAINT EP_PERSON_PK PRIMARY KEY (PE_ID)
);

DROP TABLE IF EXISTS public.EP_USER_STATUS;
CREATE TABLE IF NOT EXISTS public.EP_USER_STATUS
(
    US_ID          NUMERIC(38, 0) NOT NULL,
    US_UUID        VARCHAR(36)    NOT NULL,
    US_CODE        VARCHAR(30)    NOT NULL,
    US_NAME        VARCHAR(50)    NOT NULL,
    US_DESCRIPTION VARCHAR(100),
    CONSTRAINT EP_USER_STATUS_PK PRIMARY KEY (US_ID),
    CONSTRAINT EP_USER_STATUS_UN1 UNIQUE (US_UUID),
    CONSTRAINT EP_USER_STATUS_UN2 UNIQUE (US_CODE),
    CONSTRAINT EP_USER_STATUS_UN3 UNIQUE (US_NAME)
);


DROP TABLE IF EXISTS public.EP_USER;
CREATE TABLE IF NOT EXISTS public.EP_USER
(
    US_ID          NUMERIC(38, 0) NOT NULL,
    US_UUID        VARCHAR(36)    NOT NULL,
    US_USER_STATUS NUMERIC(38, 0) NOT NULL,
    US_USERNAME    VARCHAR(50)    NOT NULL,
    US_PASSWORD    VARCHAR(50)    NOT NULL,

    CONSTRAINT EP_USER_PK PRIMARY KEY (US_ID),
    CONSTRAINT EP_USER_UN1 UNIQUE (US_UUID),
    CONSTRAINT EP_USER_FK FOREIGN KEY (US_USER_STATUS) REFERENCES EP_USER_STATUS (US_ID)
);





