DROP TABLE IF EXISTS public.EP_MODULE_STATUS;
CREATE TABLE IF NOT EXISTS public.EP_MODULE_STATUS
(
    MS_ID          NUMERIC(38, 0) NOT NULL,
    MS_UUID        VARCHAR(36)    NOT NULL,
    MS_CODE        VARCHAR(30)    NOT NULL,
    MS_NAME        VARCHAR(50)    NOT NULL,
    MS_DESCRIPTION VARCHAR(100),
    CONSTRAINT EP_MODULE_STATUS_PK PRIMARY KEY (MS_ID),
    CONSTRAINT EP_MODULE_STATUS_UN1 UNIQUE (MS_UUID),
    CONSTRAINT EP_MODULE_STATUS_UN2 UNIQUE (MS_CODE),
    CONSTRAINT EP_MODULE_STATUS_UN3 UNIQUE (MS_NAME)
);

DROP TABLE IF EXISTS public.EP_MODULE;
CREATE TABLE IF NOT EXISTS public.EP_MODULE
(
    MO_ID            NUMERIC(38, 0) NOT NULL,
    MO_UUID          VARCHAR(36)    NOT NULL,
    MO_MODULE_STATUS NUMERIC(38, 0) NOT NULL,
    MO_NAME          VARCHAR(50)    NOT NULL,
    MO_CREATE_DATE   TIMESTAMP(6)   NOT NULL,
    MO_UPDATE_DATE   TIMESTAMP(6),
    CONSTRAINT EP_MODULE_PK PRIMARY KEY (MO_ID),
    CONSTRAINT EP_MODULE_UN1 UNIQUE (MO_UUID),
    CONSTRAINT EP_MODULE_UN2 UNIQUE (MO_NAME),
    CONSTRAINT EP_MODULE_FK FOREIGN KEY (MO_MODULE_STATUS) REFERENCES EP_MODULE_STATUS (MS_ID)
);



DROP TABLE IF EXISTS public.EP_PERSON;
CREATE TABLE IF NOT EXISTS public.EP_PERSON
(
    PE_ID       NUMERIC(38, 0) NOT NULL,
    PE_NAME     VARCHAR(50)    NOT NULL,
    PE_LASTNAME VARCHAR(50)    NOT NULL,
    PE_DOB      TIMESTAMP(6)   NOT NULL,
    CONSTRAINT EP_PERSON_PK PRIMARY KEY (PE_ID)
);

DROP TABLE IF EXISTS public.EP_USER_STATUS;
CREATE TABLE IF NOT EXISTS public.EP_USER_STATUS
(
    US_ID          NUMERIC(38, 0) NOT NULL,
    US_UUID        VARCHAR(36)    NOT NULL,
    US_CODE        VARCHAR(30)    NOT NULL,
    US_NAME        VARCHAR(50)    NOT NULL,
    US_DESCRIPTION VARCHAR(100),
    CONSTRAINT EP_USER_STATUS_PK PRIMARY KEY (US_ID),
    CONSTRAINT EP_USER_STATUS_UN1 UNIQUE (US_UUID),
    CONSTRAINT EP_USER_STATUS_UN2 UNIQUE (US_CODE),
    CONSTRAINT EP_USER_STATUS_UN3 UNIQUE (US_NAME)
);


DROP TABLE IF EXISTS public.EP_USER;
CREATE TABLE IF NOT EXISTS public.EP_USER
(
    US_ID          NUMERIC(38, 0) NOT NULL,
    US_UUID        VARCHAR(36)    NOT NULL,
    US_USER_STATUS NUMERIC(38, 0) NOT NULL,
    US_USERNAME    VARCHAR(50)    NOT NULL,
    US_PASSWORD    VARCHAR(50)    NOT NULL,

    CONSTRAINT EP_USER_PK PRIMARY KEY (US_ID),
    CONSTRAINT EP_USER_UN1 UNIQUE (US_UUID),
    CONSTRAINT EP_USER_FK FOREIGN KEY (US_USER_STATUS) REFERENCES EP_USER_STATUS (US_ID)
);

DROP TABLE IF EXISTS EP_UNIT;

DROP TABLE IF EXISTS EP_BRIGADE;

DROP TABLE IF EXISTS EP_DIVISION;

DROP TABLE IF EXISTS EP_DIVISION_STATUS;


--ACTIVATED
--DISABLED
CREATE TABLE EP_DIVISION_STATUS
(
    DS_ID          NUMERIC(38, 0) NOT NULL,
    DS_UUID        VARCHAR(36)    NOT NULL,
    DS_CODE        VARCHAR(9)     NOT NULL,
    DS_NAME        VARCHAR(9)     NOT NULL,
    DS_DESCRIPTION VARCHAR(20),
    CONSTRAINT EP_DIVISION_STATUS_PK PRIMARY KEY (DS_ID),
    CONSTRAINT EP_DIVISION_STATUS_UN1 UNIQUE (DS_UUID),
    CONSTRAINT EP_DIVISION_STATUS_UN2 UNIQUE (DS_CODE),
    CONSTRAINT EP_DIVISION_STATUS_UN3 UNIQUE (DS_NAME)
);
CREATE TABLE EP_DIVISION
(
    DI_ID           NUMERIC(38, 0) NOT NULL,
    DI_UUID         VARCHAR(36)    NOT NULL,
    DI_STATUS       NUMERIC(38, 0) NOT NULL,
    DI_CODE         VARCHAR(2)     NOT NULL,
    DI_NAME         VARCHAR(60)    NOT NULL,
    DI_DESCRIPTION  VARCHAR(120),
    DI_CREATED_DATE TIMESTAMP(6)   NOT NULL,
    DI_UPDATED_DATE TIMESTAMP(6),
    CONSTRAINT EP_DIVISION_PK PRIMARY KEY (DI_ID),
    CONSTRAINT EP_DIVISION_UN1 UNIQUE (DI_UUID),
    CONSTRAINT EP_DIVISION_UN2 UNIQUE (DI_CODE),
    CONSTRAINT EP_DIVISION_UN3 UNIQUE (DI_NAME),
    CONSTRAINT EP_DIVISION_FK FOREIGN KEY (DI_STATUS) REFERENCES EP_DIVISION_STATUS (DS_ID)
);
CREATE TABLE EP_BRIGADE
(
    BR_ID           NUMERIC(38, 0) NOT NULL,
    BR_UUID         VARCHAR(36)    NOT NULL,
    BR_DIVISION_ID  NUMERIC(38, 0) NOT NULL,
    BR_CODE         VARCHAR(4)     NOT NULL,
    BR_NAME         VARCHAR(60)    NOT NULL,
    BR_DESCRIPTION  VARCHAR(120),
    BR_CREATED_DATE TIMESTAMP(6)   NOT NULL,
    BR_UPDATED_DATE TIMESTAMP(6),
    CONSTRAINT EP_BRIGADE_PK PRIMARY KEY (BR_ID),
    CONSTRAINT EP_BRIGADE_UN1 UNIQUE (BR_UUID),
    CONSTRAINT EP_BRIGADE_UN2 UNIQUE (BR_CODE),
    CONSTRAINT EP_BRIGADE_UN3 UNIQUE (BR_NAME),
    CONSTRAINT EP_BRIGADE_FK1 FOREIGN KEY (BR_DIVISION_ID) REFERENCES EP_DIVISION (DI_ID)
);
CREATE TABLE EP_UNIT
(
    UN_ID             NUMERIC(38, 0) NOT NULL,
    UN_UUID           VARCHAR(36)    NOT NULL,
    UN_BRIGADE_STATUS NUMERIC(38, 0) NOT NULL,
    UN_CODE           VARCHAR(6)     NOT NULL,
    UN_NAME           VARCHAR(60)    NOT NULL,
    UN_DESCRIPTION    VARCHAR(120),
    UN_CREATED_DATE   TIMESTAMP(6)   NOT NULL,
    UN_UPDATED_DATE   TIMESTAMP(6),
    CONSTRAINT EP_UNIT_PK PRIMARY KEY (UN_ID),
    CONSTRAINT EP_UNIT_UN1 UNIQUE (UN_UUID),
    CONSTRAINT EP_UNIT_UN2 UNIQUE (UN_CODE),
    CONSTRAINT EP_UNIT_UN3 UNIQUE (UN_NAME),
    CONSTRAINT EP_UNIT_FK FOREIGN KEY (UN_BRIGADE_STATUS) REFERENCES EP_BRIGADE (BR_ID)
);




